name: Manual Deploy to Firebase

on:
  workflow_dispatch:
    inputs:
      release_notes:
        type: string
        required: true
        description: Release Notes

jobs:
  build:
    name: Building and distributing app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build debug version
        run: ./gradlew assembleDebug

      - name: Upload Artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID_DEBUG }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT_DEBUG }}
          groups: testers
          file: app/build/outputs/apk/debug/app-debug.apk
          releaseNotes: ${{ inputs.release_notes }}